# -*- coding: utf-8 -*-
"""ocr_trial1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGF9iub0ruMHcLeXXcQ2qYmxOYfdM-kU
"""

!pip3 install torch torchvision torchaudio

!pip install easyocr

import easyocr
import cv2
import numpy as np
import matplotlib.pyplot as plt

img1='/content/sample_data/ocrolus.jpg'
img2='/content/sample_data/hand1.jpeg'

reader = easyocr.Reader(['en'], gpu=False)
result= reader.readtext(img2)

result

result2= reader.readtext(img1)
result2

image= cv2.imread(img1)
for detection in result2:
  topleft= tuple([int(val) for val in detection [0][0]])
  bottomright= tuple([int(val) for val in detection [0][2]])
  text= detection[1]
  font=cv2.FONT_HERSHEY_SIMPLEX
  image=cv2.rectangle(image,topleft, bottomright, (255,0,255), 5)
  image=cv2.putText(image, text, topleft, font, 2, (0,0,0), 3, cv2.LINE_AA, False)
plt.figure(figsize=(20,20))
plt.imshow(image)
plt.show()
result2

